print("-ESERCIZIO 8-")
print("INGLESE                     | ITALIANO")
print("Good morning                | Buongiorno")
print("It is a pleasure to met you | È un piacere incontrarti")
print("Please call me tomorrow     | Per favore, chiamami domani")
print("Have a nice day!            | Buona giornata!")
